### ISSUE TITLE
Memory leak in RestClient

### ISSUE THREAD

**Issue by giomaik** [NimaAra/Easy.Common#21]
Hello,

The RestClient implementation seems to be leaking memory, fairly slowly in our case to be honest. Unfortunately, we have now switched to core 2.1 and httpClientFactory, which fixed the leak, so didn't look into the issue thoroughly enough. I suspect it is related to keeping the endpoints in memory. Hope this helps, let me know if I can provide any more useful info.

**Comment by NimaAra** [comment]
Thank you for reporting this.

Can I assume you were using a version older than [2.9.9](https://www.nuget.org/packages/Easy.Common/2.9.9)? I fixed #18 which may have been the cause of the leak among other issues.

**Comment by giomaik** [comment]
No worries. I was using the latest version so 2.9.9. To be honest, looking at the code, I couldn't see how a memory leak could happen unless there was an unlimited amount of endpoints to which the app would send requests. In any case, the data suggest that there was a leak that stopped as soon as I removed RestClient. It might be a good idea to limit the size of the endpoint cache to make memory consumption predictable.

**Comment by NimaAra** [comment]
I am not convinced that the leak was due to the endpoint caching unless you were hitting a very large amount of endpoints which are unique across the _scheme_|_dns-name_|_port_ which I don't think you were.

I am in the process of making further changes to the `RestClient` to bring it inline with `HttpClientFactory` introduced in `netcoreapp2.1` which eliminates the need for endpoint caching altogether but it would be useful if you could provide a repro for platforms other than `netcoreapp2.1`.
